### ISSUE TITLE
535 Authentication failed

### ISSUE THREAD

**Issue by julio-design** [cckuan2718/emailwiz#1]
Hi, I'm new to openBSD.

The server can receive mail but not send it, giving a `535 Authentication failed` error. How can I troubleshoot this error? 

By the way, I'm also using [muttwizard](https://github.com/lukesmithxyz/mutt-wizard) and have no errors in setting it up. 

Thanks

**Comment by cckuan2718** [comment]
Can you post your msmtp configuration?

**Comment by julio-design** [comment]
Solved

I didn't realize that the `user` in the `msmtprc` was with full address (`user@domain.tld`) instead of just the name (`user`).

The new version of muttwizard doesn't ask for the user and puts the address instead. But is weird that the setup was ok though.

Thanks!
